import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/nav";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Web partners",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" {inter.className} ">
        <div className="flex-1 h-[80vh]">
          <Nav />
          {children}
        </div>
            </body>
    </html>
  );
}
